import { Track } from '../types';

export class RadioService {
  static getRadioStations(): Track[] {
    return [
      {
        id: 'radio-1',
        title: 'Lofi Hip Hop Radio (Beats to Relax/Study)',
        artist: 'Lofi Girl',
        album: 'Live Radio',
        filePath: 'https://stream.zeno.fm/f3wvbbqmdg8uv',
        durationSeconds: 0,
        dominantColorHex: '#ec4899',
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
        isFavorite: false,
        addedAt: new Date().toISOString(),
        isRadio: true,
      },
      {
        id: 'radio-2',
        title: 'Synthwave / Cyberpunk FM',
        artist: 'Nightride FM',
        album: 'Live Radio',
        filePath: 'https://stream.nightride.fm/nightride.m4a',
        durationSeconds: 0,
        dominantColorHex: '#8b5cf6',
        coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
        isFavorite: false,
        addedAt: new Date().toISOString(),
        isRadio: true,
      },
      {
        id: 'radio-3',
        title: 'Classical Masterpieces & Symphony',
        artist: 'Venice Classic Radio',
        album: 'Live Radio',
        filePath: 'https://stream.zeno.fm/7x35bfe2tv8uv',
        durationSeconds: 0,
        dominantColorHex: '#d97706',
        coverUrl: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=600&q=80',
        isFavorite: false,
        addedAt: new Date().toISOString(),
        isRadio: true,
      },
      {
        id: 'radio-4',
        title: 'Deep House & Electronic Chill',
        artist: 'Deep House Lounge',
        album: 'Live Radio',
        filePath: 'https://stream.zeno.fm/0r0xa792kwzuv',
        durationSeconds: 0,
        dominantColorHex: '#06b6d4',
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        isFavorite: false,
        addedAt: new Date().toISOString(),
        isRadio: true,
      },
      {
        id: 'radio-5',
        title: 'Jazz 24 Seattle',
        artist: 'Seattle Jazz FM',
        album: 'Live Radio',
        filePath: 'https://live.wostreaming.net/direct/ppm-jazz24aac256-ibc1',
        durationSeconds: 0,
        dominantColorHex: '#10b981',
        coverUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&q=80',
        isFavorite: false,
        addedAt: new Date().toISOString(),
        isRadio: true,
      },
    ];
  }
}
